check_fast_fails

diff --git a/bbl-up/task b/bbl-up/task
--- a/bbl-up/task
+++ b/bbl-up/task
@@ -1,5 +1,28 @@
 #!/bin/bash -xeu
 
+function check_fast_fails() {
+  set +x
+  if [ -z "${LB_DOMAIN}" -a "${BBL_IAAS}" == "gcp" ]; then
+    echo "\$LB_DOMAIN is a required parameter for gcp.  Please set the domain."
+    exit 1
+  fi
+
+  if [ -z "${BBL_LB_CERT}"  ]; then
+    echo "\$BBL_LB_CERT is a required parameter"
+    exit 1
+  fi
+
+  if [ -z "${BBL_LB_KEY}"  ]; then
+    echo "\$BBL_LB_KEY is a required parameter"
+    exit 1
+  fi
+
+  if [ -n "${LB_DOMAIN}" -a "${BBL_IAAS}" == "aws" ]; then
+    echo "\$LB_DOMAIN is not honored for aws"
+  fi
+  set -x
+}
+
 function write_service_account_key() {
   set +x
   if [ ! -f "${BBL_GCP_SERVICE_ACCOUNT_KEY}" ]; then
@@ -10,6 +33,10 @@ function write_service_account_key() {
 }
 
 function main() {
+
+	check_fast_fails
+	
+	bbl version
 
 	pwd
 	ls
@@ -26,9 +53,9 @@ function main() {
 	echo ${BBL_LB_KEY}
 	echo ${LB_DOMAIN}
 	echo ${BBL_ENV_NAME}
-	cat bbl-state/${BBL_GCP_SERVICE_ACCOUNT_KEY}
+	cat ${BBL_GCP_SERVICE_ACCOUNT_KEY}
 	
-    bbl --debug up --gcp-service-account-key bbl-state/google_account_creds.json
+    bbl --debug up
 }
 
 main ${PWD}
